### PR TITLE
Scrapes page "Egyptian Arabic proverbs"

### PR DESCRIPTION
**Pull request by abd0-omar**
scrapes the mentioned page and adds it's csv to the csv directory

### CODE REVIEW

**Review by selmetwa — CHANGES_REQUESTED** [review]
Hey Abdo, thanks for the PR. Code looks good, can you include a list of steps in your pull  request so I run and test this locally?

**Comment by abd0-omar** [comment]
Sure thing, on it.

**Comment by abd0-omar** [comment]
> Hey Abdo, thanks for the PR. Code looks good, can you include a list of steps in your pull request so I run and test this locally?

I think I miss interpreted the question

Create a new project using Cargo:


``` bash
cargo new <project_name>
```

Add the following dependencies to the Cargo.toml file:

``` toml
csv = "1.3.0"
reqwest = { version = "0.12.3", features = ["blocking"] }
scraper = "0.19.0"
serde = { version = "1.0.197", features = ["derive"] }
```

Copy and paste the main file.

**Comment by selmetwa** [comment]
> > Hey Abdo, thanks for the PR. Code looks good, can you include a list of steps in your pull request so I run and test this locally?
> 
> I think I miss interpreted the question
> 
> Create a new project using Cargo:
> 
> ```shell
> cargo new <project_name>
> ```
> 
> Add the following dependencies to the Cargo.toml file:
> 
> ```toml
> csv = "1.3.0"
> reqwest = { version = "0.12.3", features = ["blocking"] }
> scraper = "0.19.0"
> serde = { version = "1.0.197", features = ["derive"] }
> ```
> 
> Copy and paste the main file.

Looking at this again I think we should stick to one language to reduce overall complexity. I don't think it makes sense to have a codebase with both node and rust for a project this small.

**Comment by abd0-omar** [comment]
Understandable, and it was a fun learning experience nonetheless. A great project btw.

**Pull request closed without merging**
